### ISSUE TITLE
RT Ethernet with custom packages

### ISSUE THREAD

**Issue by choeffer** [HilscherAutomation/netPI-netx-ethernet-lan#1]
Based on this docker image, is it possible to sent custom Ethernet packages e.g. with 7 micro seconds pause between each to simulate 97% network load?
The task is to simulate e.g. 97% or 95% network load with a constant package flow. Jitter of 1-2 mico seconds would not be an issue, but 90-110 packages each milli second would be. In average it would be 100 packages per milli second but not with a constant rate. 
As the netPI is suitable for RT communication, it would be interesting to know if custom applications with this requirements can be created.

**Comment by hilschernetpi** [comment]
I am sorry to say that this is not possible with netPI's overall structure. The netPI CPU is coupled to the netX chip across an SPI serial connection at a clock of 24Mhz by default and that is a bottle neck since all Ethernet Frames have pass this interface.

It is correct that netX chip itself could deal such a frame package rate, if the application would be inside netX or a different netX chip (netX100) would have been used that is supporting DMA transmissions with the host processor ... but not with netPI unfortunately.
